site_name: Paul Garrett PhD
theme: readthedocs
repo_url: 'https://github.com/paulgarrettphd/PaulGarrettPhD.git'
repo_name: 'GitHub'
docs_dir: markdown_docs
site_favicon: img/favicon.ico


pages:
  - General Introduction: introduction.md
  - Systems Factorial Technology (SFT): SystemsFactorialTechnology.md
  - SFT With Matlab Package: 
      - Simulating Data: SFTwMatlab\SimulatingData.md
      - Simulating Architectures: SFTwMatlab\SimulatingArchitectures.md
      - Assessing Architecture: SFTwMatlab\AssessingArchitecture.md
      - Assessing Capacity: SFTwMatlab\AssessingCapacityTBD.md
  - Systems of Numerical Cognition: systemsofnumericalcognition.md
  - Breaking the Rules: breakingtherules.md
  - Contact and Support: support.md
  - Help: index.md
  - References: References.md
  - Publications: Publications.md